# Logistic Regression

## Definition

Logistic regression is a statistical model and a type of regression analysis used for **binary classification tasks**, where the goal is to predict a binary outcome (usually denoted as 0 or 1, Yes or No, True or False, etc.) based on one or more independent variables (features or predictors). 

$$
P(Y = 1|X) = \frac{1}{1 + e^{-(\beta_0 + \beta_1X_1 + \beta_2X_2 + \ldots + \beta_pX_p)}}
$$

In this formula:

- $(P(Y = 1|X))$represents the probability of the binary outcome $Y$ being equal to 1 given the values of the independent variables $X$.
- $\beta$ is the intercept or bias term.
- $\beta_1$, $\beta_2$, $\ldots$, $\beta_p$ are the coefficients associated with the independent variables $X_1$, $X_2$, $\ldots$, $X_p$.

This formula calculates the probability that the binary outcome is 1 based on a linear combination of the independent variables, transformed using the **sigmoid (logistic) function** to ensure that the predicted probability is between 0 and 1. The values of the coefficients $\beta$ are estimated from the training data using maximum likelihood estimation.

The sigmoid activation function is the following:
$$
\sigma(x) = \frac{1}{1 + e^{-x}}
$$

In this formula:

- $\sigma(x)$ represents the sigmoid function.
- $x$ is the input to the sigmoid function.
- $e$ is the base of the natural logarithm (approximately equal to 2.71828).

## Assumptions

1. **Linearity of the Log-Odds:**
   - Logistic regression assumes that the log-odds of the binary outcome is a linear combination of the predictor variables. The relationship between independent variables and log-odds should be linear.

2. **Independence of Observations:**
   - Observations should be independent of each other. This means that the values of the binary outcome for one observation should not be influenced by the values of the binary outcome for other observations. 

3. **No or Little Multicollinearity:**
   - Multicollinearity, where predictor variables are highly correlated, should be avoided. High multicollinearity can lead to unstable coefficient estimates.

4. **Large Sample Size:**
   - A sufficiently large sample size is important for reliable parameter estimation and hypothesis testing. A guideline is to have at least 10-20 observations per predictor variable.

5. **Binary or Ordinal Dependent Variable:**
   - Logistic regression is designed for binary or ordinal (ordered categorical) dependent variables. If your dependent variable is continuous or nominal, consider other modeling techniques.

7. **No Perfect Separation:**
   - Perfect separation, where one or more independent variables perfectly predict the outcome, should be avoided. In such cases, the maximum likelihood estimates may not converge.

## Algorithm

Deriving the optimal solution for logistic regression involves finding the parameter values that best fit the data. This is typically done using a method called Maximum Likelihood Estimation (MLE). Let's go through the derivation step by step in LaTeX.

Logistic Regression Model
$$
   P(y=1|x) = \frac{1}{1 + e^{-\theta^T x}}
$$

Likelihood Function. The likelihood function measures how likely the observed data is, given the parameters of the model. For logistic regression, the likelihood $L$is the product of probabilities assigned to all individual observations:
$$
   \ell(\theta) = \prod_{i=1}^{n} P(y_i|x_i)^{y_i} (1 - P(y_i|x_i))^{(1 - y_i)}
$$

Log-Likelihood. It's easier to maximize the log of the likelihood function, as it turns the product into a sum, simplifying the computation. The log-likelihood $\ell(\theta)$ is given by:
$$ln(\ell(\theta)) = \sum_{i=1}^{n} \ln(P(y_i|x_i)^{y_i}(1 - P(y_i|x_i)^{(1 - y_i)})$$
$$ln(\ell(\theta)) = \sum_{i=1}^{n} y_i \ln(P(y_i|x_i)) + (1 - y_i) \ln(1 - P(y_i|x_i))$$
$$ln(\ell(\theta)) = \sum_{i=1}^{n} y_i \ln(\frac{1}{1 + e^{-\theta x_i}}) + (1 - y_i) \ln(1 - \frac{1}{1 + e^{-\theta x_i}})$$
$$ln(\ell(\theta)) = \sum_{i=1}^{n} y_i[\ln(\frac{1}{1+e^{-\theta x_i}}) - \ln(\frac{e^{-\theta x_i}}{1+e^{-\theta x_i}})] + \ln(\frac{e^{-\theta x_i}}{1+e^{-\theta x_i}})$$
$$ln(\ell(\theta)) = \sum_{i=1}^{n} y_i\ln(e^{\theta x_i}) + \ln(\frac{1}{1+e^{\theta x_i}})$$
$$ln(\ell(\theta)) = \sum_{i=1}^{n} y_i\theta x_i - \ln(1+e^{\theta x_i})$$

Get gradient of log-likehood
$$\nabla_\theta \ell(\theta) = \sum_{i=1}^{n} y_i x_i - \frac{1}{1+e^{\theta x_i}}*e^{\theta x_i}*x_i$$
$$\nabla_\theta \ell(\theta) = \sum_{i=1}^{n} (y_i - P(y_i|x_i))x_i$$

Gradient Ascent. To find the parameters $\theta$ that maximize the log-likelihood, we use gradient ascent (the counterpart of gradient descent used in minimization problems).
$$
   \theta := \theta + \alpha \nabla_\theta \ell(\theta)
$$

Convergence Criteria. This iterative process continues until convergence, which can be determined by a small change in the value of the log-likelihood between iterations, or until a maximum number of iterations is reached.

## Code

### Numpy Version

In [1]:
import warnings
warnings.filterwarnings('ignore')
from datasets import load_dataset
import numpy as np
import pandas as pd
import sklearn
from logistic_regression_numpy import *

In [2]:
dataset = load_dataset("imodels/diabetes-readmission", split='train')
df = dataset.to_pandas()
df.head(20)

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0                2.0                38.0             3.0             27.0   
1                4.0                48.0             0.0             11.0   
2                2.0                28.0             0.0             15.0   
3                4.0                44.0             0.0             10.0   
4                3.0                54.0             0.0              8.0   
5                3.0                43.0             0.0              7.0   
6                4.0                24.0             6.0             11.0   
7                6.0                45.0             0.0             24.0   
8                1.0                 4.0             0.0              3.0   
9                1.0                29.0             4.0             11.0   
10               1.0                17.0             0.0              8.0   
11               2.0                71.0             0.0              4.0   
12               1.0                11.0             1.0             19.0   
13              13.0                33.0             1.0             14.0   
14               6.0                59.0             0.0              2.0   
15               2.0                33.0             0.0             10.0   
16               9.0                 2.0             2.0             16.0   
17               5.0                55.0             0.0             11.0   
18               9.0                 2.0             0.0             16.0   
19               5.0                 6.0             0.0              7.0   

    number_outpatient  number_emergency  number_inpatient  number_diagnoses  \
0                 0.0               1.0               2.0               7.0   
1                 0.0               0.0               0.0               9.0   
2                 0.0               3.0               4.0               9.0   
3                 0.0               0.0               0.0               7.0   
4                 0.0               0.0               0.0               8.0   
5                 0.0               0.0               0.0               5.0   
6                 0.0               0.0               0.0               5.0   
7                 0.0               0.0               3.0               9.0   
8                 0.0               0.0               0.0               9.0   
9                 0.0               0.0               0.0               7.0   
10                0.0               0.0               0.0               8.0   
11                0.0               0.0               0.0               3.0   
12                0.0               0.0               0.0               3.0   
13                1.0               0.0               1.0               4.0   
14                0.0               0.0               0.0               9.0   
15                0.0               0.0               0.0               5.0   
16                0.0               0.0               1.0               9.0   
17                0.0               0.0               3.0               8.0   
18                0.0               0.0               1.0               7.0   
19                0.0               0.0               1.0               9.0   

    change  diabetesMed  ...  glyburide-metformin:Up  A1Cresult:>7  \
0      1.0          1.0  ...                     0.0           0.0   
1      0.0          0.0  ...                     0.0           0.0   
2      0.0          1.0  ...                     0.0           0.0   
3      0.0          1.0  ...                     0.0           0.0   
4      1.0          1.0  ...                     0.0           0.0   
5      0.0          1.0  ...                     0.0           0.0   
6      0.0          1.0  ...                     0.0           0.0   
7      1.0          1.0  ...                     0.0           0.0   
8      0.0          0.0  ...                     0.0           0.0   
9      1.0          1.0  .

In [3]:
X = np.array(df.iloc[:,:-1])
y = np.array(df.iloc[:,-1])
print(X.shape)
print(y.shape)

(81410, 150)
(81410,)


In [10]:
theta = model_fit(X,y,0.0001,100000)

0 0.538570200221103
1000 0.5469598329443557
2000 0.5602382999631494
3000 0.5712320353764894
4000 0.5784178847807395
5000 0.585075543545019
6000 0.5896081562461614
7000 0.5936617123203538
8000 0.596364083036482
9000 0.5987470826679769
10000 0.6005896081562462
11000 0.6023215821152192
12000 0.6040412725709372
13000 0.6053064734062155
14000 0.6063874216926668
15000 0.6073332514433116
16000 0.6079351431028129
17000 0.6088195553371821
18000 0.6092494779511116
19000 0.6095442820292347
20000 0.609863653113868
21000 0.6103795602505835
22000 0.6110305859231052
23000 0.611288539491463
24000 0.6114973590468001
25000 0.6117553126151578
26000 0.6119764156737502
27000 0.6122220857388527
28000 0.6125537403267411
29000 0.612823977398354
30000 0.6133398845350694
31000 0.6134750030708758
32000 0.6137452401424887
33000 0.6139663432010809
34000 0.6140891782336322
35000 0.6141505957499078
36000 0.6144085493182656
37000 0.6145928018670925
38000 0.6148139049256848
39000 0.614740203906154
40000 0.614838471932

In [11]:
intercept = np.ones((X.shape[0], 1))
X_numpy = np.concatenate((intercept, X), axis=1)
predict(theta, X_numpy[0])

True

In [13]:
predict(theta, X_numpy[0:5])

array([ True, False,  True, False, False])

In [20]:
predict_prob(theta, X_numpy[0])

0.5903616225508848

### Sklearn Version

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
# Create a Logistic Regression model
model = LogisticRegression()

# Fit the model on the training data
model.fit(X, y)

LogisticRegression()

In [17]:
model.predict(X[0].reshape(1,-1))

array([1])

In [18]:
model.predict(X[0:2])

array([1, 0])

In [21]:
y_pred = model.predict(X)

In [22]:
# Calculate accuracy
accuracy = accuracy_score(y, y_pred)
print(f'Accuracy: {accuracy}')

# Generate a confusion matrix
conf_matrix = confusion_matrix(y, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

# Generate a classification report
class_report = classification_report(y, y_pred)
print('Classification Report:')
print(class_report)

Accuracy: 0.6273307947426606
Confusion Matrix:
[[34035  9810]
 [20529 17036]]
Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.78      0.69     43845
           1       0.63      0.45      0.53     37565

    accuracy                           0.63     81410
   macro avg       0.63      0.61      0.61     81410
weighted avg       0.63      0.63      0.62     81410

